dataset:
  repo_id: lava8888/ArrangeVegetables # Repository ID
  root: ./ArrangeVegetables # Your root for data file!
policy:
  type : smolvla
  chunk_size: 5
  n_action_steps: 5
  device: cuda
  
save_checkpoint: true
output_dir: ./ckpt/smolvla_omy # Save directory
batch_size: 375
job_name : smolvla_2
resume: false 
seed : 42
num_workers: 24
steps: 20_000 # 20k steps
eval_freq: 5 # No evaluation
log_freq: 1 # Log every 10 steps
save_checkpoint: true
save_freq: 500
use_policy_training_preset: true
  
wandb:
  enable: true
  project: smolVLA
  entity: qualiastudios
  disable_artifact: true
  mode: online # Set to "online" if you want to log to WandB in real-time
  run_id: 3
  notes: first