dataset:
  repo_id: lava8888/PnPStoveToCounter # Repository ID
  root: ./PnPStoveToCounter # Your root for data file!
policy:
  type : smolvla
  chunk_size: 5
  n_action_steps: 5
  device: cuda
  
save_checkpoint: true
output_dir: ./ckpt/smolvla_omy # Save directory
batch_size: 64
job_name : smolvla_32
resume: false 
seed : 42
num_workers: 18
steps: 6_000 # 1k steps
eval_freq: -1 # No evaluation
log_freq: 5 # Log every 10 steps
save_checkpoint: true
save_freq: 400
use_policy_training_preset: true
  
wandb:
  enable: true
  project: smolVLA_65_batchsize
  entity: qualiastudios
  disable_artifact: true
  mode: online # Set to "online" if you want to log to WandB in real-time
  run_id: 31
  notes: first